### ISSUE TITLE
Shit's fucked

### ISSUE THREAD

**Issue by Not-Stabby** [mrianmerry/roll20-character-sheets#1]
- [ ] The tabs are all fucked up on firefox. The text doesn't display, so you've just got bunch of dots you click on. It's hell to navigate. I guess you're making a new one, so uhhh... just make sure it works on firefox I guess?

- [ ] For that matter, there's too many damn tabs! It would be nice if some of them could be merged, especially some of the less important ones.

- [ ] It would be fucking rad if the thing calculated your total CP and weight for you. Is that too much to ask? I have no idea.

**Comment by mrianmerry** [comment]
I do not know why syncing the fork with the roll20 repo causes all this clutter, so I'm just gonna close this and hope for the best lol
